// <auto-generated />
using System;
using Bitsion.ContextData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bitsion.ContextData.Migrations
{
    [DbContext(typeof(BitsionDB))]
    [Migration("20220114205754_DbCreate")]
    partial class DbCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bitsion.Entities.Models.Client", b =>
                {
                    b.Property<int>("cli_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("cli_Active")
                        .HasColumnType("bit");

                    b.Property<bool>("cli_Diabetic")
                        .HasColumnType("bit");

                    b.Property<string>("cli_Diseases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("cli_Drive")
                        .HasColumnType("bit");

                    b.Property<string>("cli_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("cli_UseGlasses")
                        .HasColumnType("bit");

                    b.Property<int?>("cli_doc_Documentdoc_Id")
                        .HasColumnType("int");

                    b.Property<int?>("cli_gen_Gendergen_Id")
                        .HasColumnType("int");

                    b.HasKey("cli_Id");

                    b.HasIndex("cli_doc_Documentdoc_Id");

                    b.HasIndex("cli_gen_Gendergen_Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Bitsion.Entities.Models.DocumentType", b =>
                {
                    b.Property<int>("doc_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("doc_Document")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("doc_Id");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("Bitsion.Entities.Models.Gender", b =>
                {
                    b.Property<int>("gen_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("gen_Gender")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("gen_Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            gen_Id = 1,
                            gen_Gender = "Masculino"
                        },
                        new
                        {
                            gen_Id = 2,
                            gen_Gender = "Femenino"
                        },
                        new
                        {
                            gen_Id = 3,
                            gen_Gender = "Prefiero no decirlo"
                        },
                        new
                        {
                            gen_Id = 4,
                            gen_Gender = "Otro"
                        });
                });

            modelBuilder.Entity("Bitsion.Entities.Models.Client", b =>
                {
                    b.HasOne("Bitsion.Entities.Models.DocumentType", "cli_doc_Document")
                        .WithMany()
                        .HasForeignKey("cli_doc_Documentdoc_Id");

                    b.HasOne("Bitsion.Entities.Models.Gender", "cli_gen_Gender")
                        .WithMany()
                        .HasForeignKey("cli_gen_Gendergen_Id");

                    b.Navigation("cli_doc_Document");

                    b.Navigation("cli_gen_Gender");
                });
#pragma warning restore 612, 618
        }
    }
}
